/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.winempleados;

import javax.swing.JFrame;

/**
 *
 * @author alumno
 */
public class GestionEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form GestionEmpleados
     */
    public GestionEmpleados() {
        initComponents();
        
        buttonGroupTipoTrabajador.add(jRadioButtonJefeProyecto);
        buttonGroupTipoTrabajador.add(jRadioButtonTrabajadorHoras);
        buttonGroupTipoTrabajador.add(jRadioButtonTrabajadorMontador);
        buttonGroupTipoTrabajador.add(jRadioButtonTrabajadorMontador);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoTrabajador = new javax.swing.ButtonGroup();
        jPanelDatosTrabajador = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelActualizable1 = new javax.swing.JLabel();
        jLabelActualizable2 = new javax.swing.JLabel();
        jLabelActualizable3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldActualizable1 = new javax.swing.JTextField();
        jTextFieldActualizable2 = new javax.swing.JTextField();
        jTextFieldActualizable3 = new javax.swing.JTextField();
        jPanelTipodeTrabajador = new javax.swing.JPanel();
        jPanelTipoTrabajador = new javax.swing.JPanel();
        jRadioButtonJefeProyecto = new javax.swing.JRadioButton();
        jRadioButtonTrabajadorHoras = new javax.swing.JRadioButton();
        jRadioButtonTrabajadorMontador = new javax.swing.JRadioButton();
        jRadioButtonTrabajadorComision = new javax.swing.JRadioButton();
        jButtonAñadir = new javax.swing.JButton();
        jButtonBorrarDatos = new javax.swing.JButton();
        jPanelTrabajadoresActivos = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jListListaEmpleados = new javax.swing.JList<>();
        jLabelMensaje = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jButtonEliminarTrabajador = new javax.swing.JButton();

        jPanelDatosTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Trabajador"));

        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre.setText("Nombre:");

        jLabelApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelApellido.setText("Apellido");

        jLabelActualizable1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelActualizable1.setText(" ");

        jLabelActualizable2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelActualizable2.setText(" ");

        jLabelActualizable3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelActualizable3.setText(" ");

        jTextFieldNombre.setText(" ");

        jTextFieldApellido.setText(" ");

        jTextFieldActualizable1.setText(" ");

        jTextFieldActualizable2.setText(" ");

        jTextFieldActualizable3.setText(" ");

        javax.swing.GroupLayout jPanelDatosTrabajadorLayout = new javax.swing.GroupLayout(jPanelDatosTrabajador);
        jPanelDatosTrabajador.setLayout(jPanelDatosTrabajadorLayout);
        jPanelDatosTrabajadorLayout.setHorizontalGroup(
            jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosTrabajadorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelActualizable1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelActualizable2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelActualizable3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldActualizable1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldActualizable2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldActualizable3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanelDatosTrabajadorLayout.setVerticalGroup(
            jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosTrabajadorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActualizable1)
                    .addComponent(jTextFieldActualizable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActualizable2)
                    .addComponent(jTextFieldActualizable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActualizable3)
                    .addComponent(jTextFieldActualizable3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTipodeTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Trabajadores"));

        jPanelTipoTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Trabajador"));

        jRadioButtonJefeProyecto.setText("Jefe de Proyecto");

        jRadioButtonTrabajadorHoras.setText("Trabajador por Horas");

        jRadioButtonTrabajadorMontador.setText("Trabajador Montador");

        jRadioButtonTrabajadorComision.setText("Trabajador a Comisión");

        javax.swing.GroupLayout jPanelTipoTrabajadorLayout = new javax.swing.GroupLayout(jPanelTipoTrabajador);
        jPanelTipoTrabajador.setLayout(jPanelTipoTrabajadorLayout);
        jPanelTipoTrabajadorLayout.setHorizontalGroup(
            jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonJefeProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTrabajadorHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTrabajadorMontador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTrabajadorComision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanelTipoTrabajadorLayout.setVerticalGroup(
            jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonJefeProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrabajadorHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrabajadorMontador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrabajadorComision)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButtonAñadir.setText("Añadir");
        jButtonAñadir.setEnabled(false);
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jButtonBorrarDatos.setText("Borrar Datos");
        jButtonBorrarDatos.setEnabled(false);
        jButtonBorrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipodeTrabajadorLayout = new javax.swing.GroupLayout(jPanelTipodeTrabajador);
        jPanelTipodeTrabajador.setLayout(jPanelTipodeTrabajadorLayout);
        jPanelTipodeTrabajadorLayout.setHorizontalGroup(
            jPanelTipodeTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipodeTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTipodeTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTipodeTrabajadorLayout.createSequentialGroup()
                        .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                    .addComponent(jPanelTipoTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTipodeTrabajadorLayout.setVerticalGroup(
            jPanelTipodeTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipodeTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTipoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTipodeTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadir)
                    .addComponent(jButtonBorrarDatos))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelTrabajadoresActivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Trabajadores en Activos"));

        jListListaEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListListaEmpleados.setToolTipText("");
        jScrollPane.setViewportView(jListListaEmpleados);

        jLabelMensaje.setText("Seleccione un trabajador para ver su salario");
        jLabelMensaje.setAutoscrolls(true);

        jLabelSalario.setText("Salarario: ");

        jTextFieldSalario.setEnabled(false);

        jButtonEliminarTrabajador.setText("Eliminar Trabajador");
        jButtonEliminarTrabajador.setEnabled(false);

        javax.swing.GroupLayout jPanelTrabajadoresActivosLayout = new javax.swing.GroupLayout(jPanelTrabajadoresActivos);
        jPanelTrabajadoresActivos.setLayout(jPanelTrabajadoresActivosLayout);
        jPanelTrabajadoresActivosLayout.setHorizontalGroup(
            jPanelTrabajadoresActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajadoresActivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTrabajadoresActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMensaje)
                    .addComponent(jLabelSalario)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEliminarTrabajador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTrabajadoresActivosLayout.setVerticalGroup(
            jPanelTrabajadoresActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajadoresActivosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelMensaje)
                .addGap(18, 18, 18)
                .addComponent(jLabelSalario)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarTrabajador)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanelTrabajadoresActivosLayout.createSequentialGroup()
                .addComponent(jScrollPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDatosTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTipodeTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelTrabajadoresActivos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTipodeTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTrabajadoresActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jButtonBorrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBorrarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoTrabajador;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonBorrarDatos;
    private javax.swing.JButton jButtonEliminarTrabajador;
    private javax.swing.JLabel jLabelActualizable1;
    private javax.swing.JLabel jLabelActualizable2;
    private javax.swing.JLabel jLabelActualizable3;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JList<String> jListListaEmpleados;
    private javax.swing.JPanel jPanelDatosTrabajador;
    private javax.swing.JPanel jPanelTipoTrabajador;
    private javax.swing.JPanel jPanelTipodeTrabajador;
    private javax.swing.JPanel jPanelTrabajadoresActivos;
    private javax.swing.JRadioButton jRadioButtonJefeProyecto;
    private javax.swing.JRadioButton jRadioButtonTrabajadorComision;
    private javax.swing.JRadioButton jRadioButtonTrabajadorHoras;
    private javax.swing.JRadioButton jRadioButtonTrabajadorMontador;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextFieldActualizable1;
    private javax.swing.JTextField jTextFieldActualizable2;
    private javax.swing.JTextField jTextFieldActualizable3;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables
}
